### ISSUE TITLE
Swashbuckle.AspnetCore version

### ISSUE THREAD

**Issue by sandorfr** [geeklearningio/gl-swashbuckle#14]
The version should be detected from the current project dependencies.

**Comment by asiffermann** [comment]
Maybe it shouldn't even be referenced from the generation project...
So, we should detect at generation-time if the tool could be run for the targeted project according to Swashbuckle.AspnetCore being referenced (instead of failing restoring package).

**Comment by sandorfr** [comment]
I think I tried to not reference it in the past and it lead to other issues. using `*` as the version selector seems to do the trick.
