### ISSUE TITLE
Settings Management

### ISSUE THREAD

**Issue by sandorfr** [geeklearningio/gl-swashbuckle#15]
Currently there's no way to easily inject configuration settings. It can lead to early crash of the underlying web app just because it does not have any of the required settings.

**Comment by asiffermann** [comment]
I'm not sure if you should do anything for this issue... The content root is already well set for the TestServer.

This issue could eventually occur if the tool is run from an automated build for a project with mandatory settings in the `appsettings.development.json`. In this case, one could create this json file prior to the call of our tool as part of the build process.

BTW, I really think that missing settings should not crash a web app at startup, but should let the web app being started and then report error as response to all underlying requests (and I'm looking at me too saying that 😖)

**Comment by sandorfr** [comment]
Yes you are right, this is more the developers responsibility to provide an appropriate settings files and or use Testavior :). 

The one thing that might be very helpful though would be to add an --environment switch

**Comment by sandorfr** [comment]
--aspnetcore-environment flag is now available.
