### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by minuz** [geeklearningio/gl-swashbuckle#39]
Hi guys, 

We have been having a bit of a problem with the build server and I end up finding that there's a version mismatch between the projects.

The generated SwaggerGen project generates the following dependencies:

```
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="*" />
    <PackageReference Include="System.Runtime.Loader" Version="*" />
```
When I checked which version that would restore, it showed as everything as latest version.
Then on `GeekLearning.DotNet.Swashbuckle` I modified to the following.
``` xml
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.0" /> -- Old
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0" /> --Old
    <PackageReference Include="Swashbuckle.AspNetCore" Version="2.2.0" />
```

This seems to work...but I cannot confirm if that's the actual fix for the problem I have until I run on build server. Could you guys have a look? I can submit a pull request with those changes if necessary.

Cheers

**Comment by sandorfr** [comment]
You can try https://www.nuget.org/packages/GeekLearning.DotNet.Swashbuckle/0.5.0-alpha0020

**Comment by minuz** [comment]
Thanks! Thanks worked!!

**Comment by sandorfr** [comment]
Cool man :) thanks for trying!

**Comment by asiffermann** [comment]
It works here too, closing this issue 😉
